[manager]
prepend_keymap = [
    { on = [ "z", "c" ], run = """
        shell 'printf "Your Name:"; read name; zip -j "$name.zip" "$@"' --block --confirm
    """, desc = "Create .zip" },
    { on = [ "z", "u" ], run = """
        shell 'unzip "$@"' --block --confirm
    """, desc = "Unzip .zip"},
]
